export default {
	isHost: null,
	alias: null,
	isInLobby: false,
	isGameStarted: false,
	isSinging: false,
	isRoundStarted: false,
	turnResults: null,
	roomCode: null,
	userList: [],
	lyrics: null,
	socket: null,
	turnOrder: [],
	currentTurn: null,
	roundNumber: 0,
};
