export const CREATE_ROOM = 'CREATE_ROOM';
export const ROOM_INFO = 'ROOM_INFO';
export const ERROR_RESPONSE = 'ERROR_RESPONSE';
export const DISCONNECT = 'disconnect'; //needs to be lowercase because it is a built-in socket-io function
export const CLOSE_ROOM = 'CLOSE_ROOM';
export const JOIN_ROOM = 'JOIN_ROOM';
export const GAME_START = 'GAME_START';
export const LEAVE_ROOM = 'LEAVE_ROOM';
export const NEXT_TURN = 'NEXT_TURN';
export const PLAY_SONG = 'PLAY_SONG';
export const STOP_SONG = 'STOP_SONG';
export const START_ROUND = 'START_ROUND';
export const START_SING = 'START_SING';
export const END_TURN = 'END_TURN';
export const SELECT_SONG = 'SELECT_SONG';
