import * as SONGS from './songs';

export default {
	[SONGS.OOPS_I_DID_IT_AGAIN]: {
		songTitle: 'Oops I did it again',
		artist: 'Britney Spears',
		startTime: 41000,
		cutOffTime: 51200,
		endTime: 53700,
		spotify_uri: 'spotify:track:6naxalmIoLFWR0siv8dnQQ',
		partialLyrics: `Lost all my senses, That is just so typically me. Oh baby, baby ...`,
		fullLyrics: `Lost all my senses, That is just so typically me. Oh baby, baby. Oops I did it again...`,
		answer: `Oops I did it again`,
	},
	[SONGS.REAL_SLIM_SHADY]: {
		songTitle: 'The Real Slim Shady',
		artist: 'Eminem',
		startTime: 78500,
		cutOffTime: 83600,
		endTime: 85200,
		spotify_uri: 'spotify:track:3yfqSUWxFvZELEM4PmlwIR',
		partialLyrics: `But if you feel like I feel, I got the antidote, Women, wave your pantyhose, sing the chorus, and it goes ...`,
		fullLyrics: `But if you feel like I feel, I got the antidote, Women, wave your pantyhose, sing the chorus, and it goes I'm Slim Shady, yes I'm the real Shady ...`,
		answer: `I'm Slim Shady yes I'm the real Shady`,
	},
	[SONGS.OLD_TOWN_ROAD]: {
		songTitle: 'Old Town Road',
		artist: 'Lil Nas X',
		startTime: 77000,
		cutOffTime: 84900,
		endTime: 88000,
		spotify_uri: 'spotify:track:0F7FA14euOIX8KcbEturGH',
		partialLyrics: `Can't nobody tell me nothin', You can't tell me nothin'. Yeah...`,
		fullLyrics: `Can't nobody tell me nothin', You can't tell me nothin'. Yeah, I'm gonna take my horse to the old town road...`,
		answer: `I'm going to take my horse to the old town road`,
	},
	[SONGS.SOMEBODY_THAT_I_USED_TO_KNOW]: {
		songTitle: 'Somebody That I Used to Know',
		artist: 'Gotye',
		startTime: 114000,
		cutOffTime: 119600,
		endTime: 123000,
		spotify_uri: 'spotify:track:4wCmqSrbyCgxEXROQE6vtV',
		partialLyrics: `Have your friends collect your records and then change your number, I guess that I don't need that though...`,
		fullLyrics: `Have your friends collect your records and then change your number, I guess that I don't need that though, Now you're just somebody that I used to know...`,
		answer: `Now you're just somebody that I used to know`,
	},
	[SONGS.TIK_TOK]: {
		songTitle: 'TiK ToK',
		artist: 'Kesha',
		startTime: 36000,
		cutOffTime: 40700,
		endTime: 44900,
		spotify_uri: 'spotify:track:0HPD5WQqrq7wPWR7P7Dw1i',
		partialLyrics: `Tonight, I'ma fight, 'Til we see the sunlight...`,
		fullLyrics: `Tonight, I'ma fight, 'Til we see the sunlight, Tick-tock on the clock But the party don't stop, no`,
		answer: `Tick tock on the clock but the party don't stop`,
	},
};
