import * as SONGS from './songs';

export default {
	[SONGS.OOPS_I_DID_IT_AGAIN]: {
		songTitle: 'Oops I did it again',
		artist: 'Britney Spears',
		startTime: 41000,
		cutOffTime: 49900,
		endTime: 53400,
		spotify_uri: 'spotify:track:6naxalmIoLFWR0siv8dnQQ',
		partialLyrics: `Lost all my senses, That is just so typically me. Oh baby, baby ...`,
		fullLyrics: `Lost all my senses, That is just so typically me. Oh baby, baby. Oops I did it again...`,
		answer: `Oops I did it again`,
	},
	[SONGS.REAL_SLIM_SHADY]: {
		songTitle: 'The Real Slim Shady',
		artist: 'Eminem',
		startTime: 78500,
		cutOffTime: 82500,
		endTime: 84600,
		spotify_uri: 'spotify:track:3yfqSUWxFvZELEM4PmlwIR',
		partialLyrics: `But if you feel like I feel, I got the antidote, Women, wave your pantyhose, sing the chorus, and it goes ...`,
		fullLyrics: `But if you feel like I feel, I got the antidote, Women, wave your pantyhose, sing the chorus, and it goes I'm Slim Shady, yes I'm the real Shady ...`,
		answer: `I'm Slim Shady yes I'm the real Shady`,
	},
	[SONGS.OLD_TOWN_ROAD]: {
		songTitle: 'Old Town Road',
		artist: 'Lil Nas X',
		startTime: 77000,
		cutOffTime: 84100,
		endTime: 87500,
		spotify_uri: 'spotify:track:0F7FA14euOIX8KcbEturGH',
		partialLyrics: `Can't nobody tell me nothin', You can't tell me nothin'. Yeah...`,
		fullLyrics: `Can't nobody tell me nothin', You can't tell me nothin'. Yeah, I'm gonna take my horse to the old town road...`,
		answer: `I'm going to take my horse to the old town road`,
	},
	[SONGS.SOMEBODY_THAT_I_USED_TO_KNOW]: {
		songTitle: 'Somebody That I Used to Know',
		artist: 'Gotye',
		startTime: 114000,
		cutOffTime: 118800,
		endTime: 122500,
		spotify_uri: 'spotify:track:4wCmqSrbyCgxEXROQE6vtV',
		partialLyrics: `Have your friends collect your records and then change your number, I guess that I don't need that though...`,
		fullLyrics: `Have your friends collect your records and then change your number, I guess that I don't need that though, Now you're just somebody that I used to know...`,
		answer: `Now you're just somebody that I used to know`,
	},
	[SONGS.TIK_TOK]: {
		songTitle: 'TiK ToK',
		artist: 'Kesha',
		startTime: 36000,
		cutOffTime: 39700,
		endTime: 44900,
		spotify_uri: 'spotify:track:0HPD5WQqrq7wPWR7P7Dw1i',
		partialLyrics: `Tonight, I'ma fight, 'Til we see the sunlight...`,
		fullLyrics: `Tonight, I'ma fight, 'Til we see the sunlight, Tick-tock on the clock But the party don't stop`,
		answer: `Tick tock on the clock but the party don't stop`,
	},
	[SONGS.RADIOACTIVE]: {
		songTitle: 'Radioactive',
		artist: 'Imagine Dragons',
		startTime: 63500,
		cutOffTime: 73400,
		endTime: 77200,
		spotify_uri: 'spotify:track:4G8gkOterJn0Ywt6uhqbhp',
		partialLyrics: `Welcome to the new age, to the new age, Welcome to the new age, to the new age, Whoa, oh, oh, oh, oh, whoa, oh, oh, oh...`,
		fullLyrics: `Welcome to the new age, to the new age, Welcome to the new age, to the new age, Whoa, oh, oh, oh, oh, whoa, oh, oh, oh, I'm radioactive, radioactive...`,
		answer: `I'm radioactive radioactive`,
	},
	[SONGS.FIREWORK]: {
		songTitle: 'Firework',
		artist: 'Katy Perry',
		startTime: 46000,
		cutOffTime: 53500,
		endTime: 56900,
		spotify_uri: 'spotify:track:4lCv7b86sLynZbXhfScfm2',
		partialLyrics: `Just own the night like the 4th of July...`,
		fullLyrics: `Just own the night like the 4th of July, 'Cause baby you're a firework...`,
		answer: `cuz baby you're a firework`,
	},
	[SONGS.DYNAMITE]: {
		songTitle: 'Dynamite',
		artist: 'Tao Cruz',
		startTime: 50000,
		cutOffTime: 53200,
		endTime: 55400,
		spotify_uri: 'spotify:track:1DqdF42leyFIzqNDv9CjId',
		partialLyrics: `We gon' go all night, We gon' light it up...`,
		fullLyrics: `We gon' go all night, We gon' light it up, Like it's dynamite...`,
		answer: `like it's dynamite`,
	},
	[SONGS.GRENADE]: {
		songTitle: 'Grenade',
		artist: 'Bruno Mars',
		startTime: 29400,
		cutOffTime: 37600,
		endTime: 40600,
		spotify_uri: 'spotify:track:2tJulUYLDKOg9XrtVkMgcJ',
		partialLyrics: `To give me all your love is all I ever ask, 'Cause what you don't understand is...`,
		fullLyrics: `To give me all your love is all I ever ask, 'Cause what you don't understand is I'd catch a grenade for ya...`,
		answer: `I'd catch a grenade for ya`,
	},
	[SONGS.SOUL_SISTER]: {
		songTitle: 'Hey, Soul Sister',
		artist: 'Train',
		startTime: 40000,
		cutOffTime: 50900,
		endTime: 53400,
		spotify_uri: 'spotify:track:4HlFJV71xXKIGcU3kRyttv',
		partialLyrics: `I knew when we collided, You're the one I have decided who's one of my kind...`,
		fullLyrics: `I knew when we collided, You're the one I have decided who's one of my kind, Hey, soul sister...`,
		answer: `Hey soul sister`,
	},
	[SONGS.FANCY]: {
		songTitle: 'Fancy',
		artist: 'Iggy Azalea',
		startTime: 31000,
		cutOffTime: 37900,
		endTime: 39800,
		spotify_uri: 'spotify:track:3oiMJQAWVaxSubJ7b2VUtX',
		partialLyrics: `Rooftop like we bringin' '88 back (what), Bring the hooks in, where the bass at?, Champagne spillin', you should taste that...`,
		fullLyrics: `Rooftop like we bringin' '88 back (what), Bring the hooks in, where the bass at?, Champagne spillin', you should taste that, I'm so fancy...`,
		answer: `I'm so fancy`,
	},
	[SONGS.CHEAP_THRILLS]: {
		songTitle: 'Cheap Thrills',
		artist: 'Sia',
		startTime: 28000,
		cutOffTime: 35900,
		endTime: 37200,
		spotify_uri: 'spotify:track:3S4px9f4lceWdKf0gWciFu',
		partialLyrics: `I ain't got cash, But I got you, baby, Baby, I don't need dollar bills to have fun tonight...`,
		fullLyrics: `I ain't got cash, But I got you, baby, Baby, I don't need dollar bills to have fun tonight, I love cheap thrills...`,
		answer: `I love cheap thrills`,
	},
	[SONGS.RUDE]: {
		songTitle: 'Rude',
		artist: 'MAGIC!',
		startTime: 33400,
		cutOffTime: 41000,
		endTime: 44600,
		spotify_uri: 'spotify:track:6RtPijgfPKROxEzTHNRiDp',
		partialLyrics: `You say I'll never get your blessin' 'til the day I die, "Tough luck, my friend, but the answer is no"...`,
		fullLyrics: `You say I'll never get your blessin' 'til the day I die, "Tough luck, my friend, but the answer is no", Why you gotta be so rude?...`,
		answer: `Why you gotta be so rude`,
	},
	[SONGS.PAYPHONE]: {
		songTitle: 'Payphone',
		artist: 'Maroon 5',
		startTime: 43100,
		cutOffTime: 52300,
		endTime: 56600,
		spotify_uri: 'spotify:track:1LmN9SSHISbtp9LoaR5ZVJ',
		partialLyrics: `Still stuck in that time, When we called it love, But even the sun sets in paradise...`,
		fullLyrics: `Still stuck in that time, When we called it love, But even the sun sets in paradise, I'm at a payphone trying to call home...`,
		answer: `I'm at a payphone trying to call home`,
	},
	[SONGS.HOTLINE_BLING]: {
		songTitle: 'Hotline Bling',
		artist: 'Drake',
		startTime: 20000,
		cutOffTime: 27000,
		endTime: 29000,
		spotify_uri: 'spotify:track:0wwPcA6wtMf6HUMpIRdeP7',
		partialLyrics: `Call me on my cell phone, Late night when you need my love, And...`,
		fullLyrics: `Call me on my cell phone, Late night when you need my love, And I know when that hotline bling...`,
		answer: `I know when that hotline bling`,
	},
};
